name: Docker CI Hello World
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t my-hello-world-app .
      - name: Run Docker container and test
        run: docker run my-hello-world-app
